## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Turbat,PK,26.0023,63.0440,93.33,53,100,14.12,overcast clouds
1,1,Tazovskiy,RU,67.4667,78.7000,59.22,81,43,15.48,light rain
2,2,Snizhne,UA,48.0261,38.7723,86.20,37,12,11.18,few clouds
3,3,Tasiilaq,GL,65.6145,-37.6368,57.36,65,60,2.39,broken clouds
4,4,Oriximina,BR,-1.7656,-55.8661,87.31,48,91,2.66,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you like for the trip?"))
max_temp = float(input("What is the maximum temperature you like for the trip?"))

What is the minimum temperature you like for the trip?75
What is the maximum temperature you like for the trip?90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
2,2,Snizhne,UA,48.0261,38.7723,86.20,37,12,11.18,few clouds
4,4,Oriximina,BR,-1.7656,-55.8661,87.31,48,91,2.66,overcast clouds
5,5,Lethem,GY,3.3803,-59.7968,78.84,78,96,4.59,overcast clouds
13,13,Maceio,BR,-9.6658,-35.7353,83.64,61,40,5.75,scattered clouds
17,17,Ribeira Grande,PT,38.5167,-28.7000,75.60,73,75,12.66,broken clouds
21,21,Boda,CF,4.3189,17.4695,84.36,58,61,4.36,light rain
22,22,Dingle,PH,10.9995,122.6711,78.37,88,100,6.76,overcast clouds
25,25,Hof,DE,50.3167,11.9167,76.44,48,0,14.97,clear sky
29,29,Puerto Cabezas,NI,14.0351,-83.3888,84.16,84,75,4.61,broken clouds
36,36,Marsa Matruh,EG,31.3525,27.2453,86.20,58,0,14.97,clear sky

In [12]:
# 4a. Determine if there are any empty rows.
preferred_cities.notnull().sum()

City_ID                289
City                   289
Country                289
Lat                    289
Lng                    289
Max Temp               289
Humidity               289
Cloudiness             289
Wind Speed             289
Current Description    289
dtype: int64

In [10]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities = preferred_cities[preferred_cities["Country"].notna()]

In [13]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Snizhne,UA,86.20,few clouds,48.0261,38.7723,
4,Oriximina,BR,87.31,overcast clouds,-1.7656,-55.8661,
5,Lethem,GY,78.84,overcast clouds,3.3803,-59.7968,
13,Maceio,BR,83.64,scattered clouds,-9.6658,-35.7353,
17,Ribeira Grande,PT,75.60,broken clouds,38.5167,-28.7000,
21,Boda,CF,84.36,light rain,4.3189,17.4695,
22,Dingle,PH,78.37,overcast clouds,10.9995,122.6711,
25,Hof,DE,76.44,clear sky,50.3167,11.9167,
29,Puerto Cabezas,NI,84.16,broken clouds,14.0351,-83.3888,
36,Marsa Matruh,EG,86.20,clear sky,31.3525,27.2453,

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index,row in hotel_df.iterrows():
    

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url,params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        pass

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [16]:
# 7. Drop the rows where there is no Hotel Name.

hotel_df = hotel_df.loc[(hotel_df["Hotel Name"] != "")]

In [18]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
#<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [20]:
# 11a. Add a marker layer for each city to the map. 

locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)


# Call the figure to plot the data.
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))